### ISSUE TITLE
cannot close modal

### ISSUE THREAD

**Issue by Queenhuxna** [crazycoder-io/react-native-modal-notifier#1]
cannot close modal with another action

**Comment by mkilincaslan** [comment]
Hello @husna2540,
Sorry because of the delayed response! ://

Can you please specify what the issue is?
What do you exactly point with "_another action_"?

Because currently the package supports only 2 types of close the modal;
- By using close button
- By set `autoCloseDelay` field to a certain time to close after, while you were triggering

**Comment by mkilincaslan** [comment]
Since there is no more question and answer is fair enough for this issue to fix.
I close this issue!
